spring.datasource.url=jdbc:mariadb://readbook-db-readbook-01.i.aivencloud.com:12521/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_0yT17o4H-Be_GST3ofu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/img
spring.web.resources.static-locations=classpath:/static/,file:uploads/